# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7823d752498c942f76fd10b61162de284dab3a5ba40fe02f154709782e9d59ac9883dc5f5d389b9e9e90d306756e37c9dacf980a59e2d2756f06077dca97b60f

test:
  secret_key_base: dfb141373cf5b4f9f8028a1d7628fb80755372260e9d5b1c5b456c1e1be5fe7296f8288b0c73e5e4aedb944e9f782b3b1149897965384f3762bd35c40d12c872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
